apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: minecraft-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: minecraft-minecraft
  podMetricsEndpoints:
  - port: http-metrics